### ISSUE TITLE
Error in Python Bindings when Running Constrained Planning Examples

### ISSUE THREAD

**Issue by cohnt** [ompl/ompl#1007]
When running the example `ConstrainedPlanningSphere.py` (and commenting out the tools import, as suggested in #1006), I get the following error:
```
$ python3 ConstrainedPlanningSphere.py 
Info:    Using Projection-Based State Space!
Debug:   RRT: Planner range detected to be 1.385641
Info:    RRT: Starting planning with 1 states already in datastructure
Traceback (most recent call last):
  File ".../ompl/demos/constraint/ConstrainedPlanningSphere.py", line 160, in <module>
    spherePlanning(parser.parse_args())
  File ".../ompl/demos/constraint/ConstrainedPlanningSphere.py", line 143, in spherePlanning
    spherePlanningOnce(cp, planners[0], options.output)
  File ".../ompl/demos/constraint/ConstrainedPlanningSphere.py", line 98, in spherePlanningOnce
    stat = cp.solveOnce(output, "sphere")
  File ".../ompl/demos/constraint/ConstrainedPlanningCommon.py", line 207, in solveOnce
    stat = self.ss.solve(self.options.time)
TypeError: No Python class registered for C++ class Eigen::Ref<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::InnerStride<1> >

```

**Comment by zkingston** [comment]
Confirmed, got this same message on a fresh build. I'll take a look into this when I get the chance.
