### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'bindings/base

### ISSUE THREAD

**Issue by dbdxnuliba** [ompl/ompl#1036]
-- The following Python modules were found:

 * numpy pyplusplus pygccxml

-- Configuring done
-- Generating done
-- Build files have been written to: /home/dell/ref/ompl/ompl-db4e6bf581cd531462ce8a3fa1889a659bd1c4b0/build/Release
[100%] Built target update_control_bindings
[100%] Creating C++ code for Python module tools (see pyplusplus_tools.log)
Replacing member function ::ompl::base::OptimizationObjective::print
Replacing member function ::ompl::base::GoalRegion::print
Replacing member function ::ompl::base::Goal::print
Replacing member function ::ompl::base::ProblemDefinition::print
Replacing member function
::ompl::base::ScopedState<ompl::base::StateSpace>::print
Replacing member function ::ompl::base::Path::print
Replacing member function ::ompl::base::ProjectionMatrix::print
Replacing member function ::ompl::base::ParamSet::print
Replacing member function ::ompl::tools::SelfConfig::print
Replacing member function ::ompl::geometric::PathGeometric::print
Replacing member function ::ompl::geometric::SimpleSetup::print
Replacing member function ::ompl::control::SimpleSetup::print
Replacing member function ::ompl::control::PathControl::print
Replacing member function
::ompl::tools::Benchmark::saveResultsToStream
Replacing member function
::ompl::tools::Benchmark::setPlannerSwitchEvent
Replacing member function ::ompl::tools::Benchmark::setPreRunEvent
Replacing member function ::ompl::tools::Benchmark::setPostRunEvent
Traceback (most recent call last):
  File "/home/dell/ref/ompl/ompl-db4e6bf581cd531462ce8a3fa1889a659bd1c4b0/py-bindings/generate_bindings.py", line 983, in <module>
    globals()['ompl_'+module+'_generator_t']()
  File "/home/dell/ref/ompl/ompl-db4e6bf581cd531462ce8a3fa1889a659bd1c4b0/py-bindings/generate_bindings.py", line 880, in __init__
    code_generator_t.__init__(self, 'tools', \
  File "/home/dell/ref/ompl/ompl-db4e6bf581cd531462ce8a3fa1889a659bd1c4b0/py-bindings/ompl/bindings_generator.py", line 154, in __init__
    self.mb.register_module_dependency(dep)
  File "/usr/local/lib/python3.8/dist-packages/pyplusplus/module_builder/boost_python_builder.py", line 142, in register_module_dependency
    db.load( other_module_generated_code_dir )
  File "/usr/local/lib/python3.8/dist-packages/pyplusplus/utils/__init__.py", line 129, in load
    f = open( fpath, 'r+b' )
**FileNotFoundError: [Errno 2] No such file or directory: 'bindings/base'**
-- Build type: Release
-- Checking for module 'libspot'
--   No package 'libspot' found
-- Could NOT find spot (missing: SPOT_LIBRARIES SPOT_INCLUDE_DIRS) 
-- Code for module base not found; type "make update_bindings"
-- Code for module control not found; type "make update_bindings"
-- Code for module geometric not found; type "make update_bindings"
-- Code for module tools not found; type "make update_bindings"
-- The following features have been enabled:

 * OMPL_VERSIONED_INSTALL, Whether to install header files in
   <prefix>/include/ompl-X.Y/ompl, where X and Y are the major and minor
   version numbers
 * OMPL_BUILD_PYBINDINGS, Whether to build the Python bindings.
 * OMPL_BUILD_PYTESTS, Whether to build/run the python binding unit tests.
 * OMPL_BUILD_TESTS, Whether to build the unit tests.
 * OMPL_BUILD_DEMOS, Whether to build the OMPL demo programs.

-- The following OPTIONAL packages have been found:

**Comment by zkingston** [comment]
Can you post the entire output of `make update_bindings`? The error you are seeing is just a symptom, not the main cause of error.

**Comment by dbdxnuliba** [comment]
```
dell@dell-NUC11PAHi7:~/ref/ompl-1.6.0/build/Release$ make update_bindings
[  0%] Preparing C++ header file for Python binding generation for module control
[  0%] Built target control.h
[  0%] Preparing C++ header file for Python binding generation for module base
[  0%] Built target base.h
[ 33%] Preparing C++ header file for Python binding generation for module util
[ 33%] Built target util.h
[ 33%] Creating C++ code for Python module util (see pyplusplus_util.log)
std::vector<double, std::allocator<double> >::reference
std::vector<double, std::allocator<double> >::at(std::size_t __n)
[member function] > warning W1008: The function returns non-const
reference to "Python immutable" > type. The value cannot be modified
from Python.
std::vector<double, std::allocator<double> >::reference
std::vector<double, std::allocator<double> >::front() [member
function] > warning W1008: The function returns non-const reference to
"Python immutable" > type. The value cannot be modified from Python.
std::vector<double, std::allocator<double> >::reference
std::vector<double, std::allocator<double> >::back() [member function]
> warning W1008: The function returns non-const reference to "Python
immutable" > type. The value cannot be modified from Python.
std::vector<double, std::allocator<double> >::pointer
std::vector<double, std::allocator<double>
>::_M_allocate_and_copy(std::size_t __n,
__gnu_cxx::__normal_iterator<const double *, std::vector<double,
std::allocator<double> > > __first, __gnu_cxx::__normal_iterator<const
double *, std::vector<double, std::allocator<double> > > __last)
[member function] > compilation error W1050: The function returns
"std::vector<double, > std::allocator<double> >::pointer" type. You
have to specify a call > policies.Be sure to take a look on `Py++`
defined call policies
std::vector<unsigned int, std::allocator<unsigned int> >::reference
std::vector<unsigned int, std::allocator<unsigned int>
>::at(std::size_t __n) [member function] > warning W1008: The function
returns non-const reference to "Python immutable" > type. The value
cannot be modified from Python.
std::vector<unsigned int, std::allocator<unsigned int> >::reference
std::vector<unsigned int, std::allocator<unsigned int> >::front()
[member function] > warning W1008: The function returns non-const
reference to "Python immutable" > type. The value cannot be modified
from Python.
std::vector<unsigned int, std::allocator<unsigned int> >::reference
std::vector<unsigned int, std::allocator<unsigned int> >::back()
[member function] > warning W1008: The function returns non-const
reference to "Python immutable" > type. The value cannot be modified
from Python.
std::vector<unsigned int, std::allocator<unsigned int> >::pointer
std::vector<unsigned int, std::allocator<unsigned int>
>::_M_allocate_and_copy(std::size_t __n,
__gnu_cxx::__normal_iterator<const unsigned int *,
std::vector<unsigned int, std::allocator<unsigned int> > > __first,
__gnu_cxx::__normal_iterator<const unsigned int *,
std::vector<unsigned int, std::allocator<unsigned int> > > __last)
[member function] > compilation error W1050: The function returns
"std::vector<unsigned int, > std::allocator<unsigned int> >::pointer"
type. You have to specify a call > policies.Be sure to take a look on
`Py++` defined call policies
std::vector<ompl::PPM::Color, std::allocator<ompl::PPM::Color>
>::pointer std::vector<ompl::PPM::Color,
std::allocator<ompl::PPM::Color> >::_M_allocate_and_copy(std::size_t
__n, __gnu_cxx::__normal_iterator<const ompl::PPM::Color *,
std::vector<ompl::PPM::Color, std::allocator<ompl::PPM::Color> > >
__first, __gnu_cxx::__normal_iterator<const ompl::PPM::Color *,
std::vector<ompl::PPM::Color, std::allocator<ompl::PPM::Color> > >
__last) [member function] > compilation error W1050: The function
returns "std::vector<ompl::PPM::Color, >
std::allocator<ompl::PPM::Color> >::pointer" type. You have to specify
a call > policies.Be sure to take a look on `Py++` defined call
policies
std::vector<unsigned long, std::allocator<unsigned long> >::reference
std::vector<unsigned long, std::allocator<unsigned long>
>::at(std::size_t __n) [member function] > warning W1008: The function
returns non-const reference to "Python immutable" > type. The value
cannot be modified from Python.
std::vector<unsigned long, std::allocator<unsigned long> >::reference
std::vector<unsigned long, std::allocator<unsigned long> >::front()
[member function] > warning W1008: The function returns non-const
reference to "Python immutable" > type. The value cannot be modified
from Python.
std::vector<unsigned long, std::allocator<unsigned long> >::reference
std::vector<unsigned long, std::allocator<unsigned long> >::back()
[member function] > warning W1008: The function returns non-const
reference to "Python immutable" > type. The value cannot be modified
from Python.
std::vector<unsigned long, std::allocator<unsigned long> >::pointer
std::vector<unsigned long, std::allocator<unsigned long>
>::_M_allocate_and_copy(std::size_t __n,
__gnu_cxx::__normal_iterator<const unsigned long *,
std::vector<unsigned long, std::allocator<unsigned long> > > __first,
__gnu_cxx::__normal_iterator<const unsigned long *,
std::vector<unsigned long, std::allocator<unsigned long> > > __last)
[member function] > compilation error W1050: The function returns
"std::vector<unsigned long, > std::allocator<unsigned long>
>::pointer" type. You have to specify a call > policies.Be sure to
take a look on `Py++` defined call policies
std::vector<int, std::allocator<int> >::reference std::vector<int,
std::allocator<int> >::at(std::size_t __n) [member function] > warning
W1008: The function returns non-const reference to "Python immutable"
> type. The value cannot be modified from Python.
std::vector<int, std::allocator<int> >::reference std::vector<int,
std::allocator<int> >::front() [member function] > warning W1008: The
function returns non-const reference to "Python immutable" > type. The
value cannot be modified from Python.
std::vector<int, std::allocator<int> >::reference std::vector<int,
std::allocator<int> >::back() [member function] > warning W1008: The
function returns non-const reference to "Python immutable" > type. The
value cannot be modified from Python.
std::vector<int, std::allocator<int> >::pointer std::vector<int,
std::allocator<int> >::_M_allocate_and_copy(std::size_t __n,
__gnu_cxx::__normal_iterator<const int *, std::vector<int,
std::allocator<int> > > __first, __gnu_cxx::__normal_iterator<const
int *, std::vector<int, std::allocator<int> > > __last) [member
function] > compilation error W1050: The function returns
"std::vector<int, > std::allocator<int> >::pointer" type. You have to
specify a call policies.Be > sure to take a look on `Py++` defined
call policies
std::vector<std::basic_string<char>,
std::allocator<std::basic_string<char> > >::pointer
std::vector<std::basic_string<char>,
std::allocator<std::basic_string<char> >
>::_M_allocate_and_copy(std::size_t __n,
__gnu_cxx::__normal_iterator<const std::basic_string<char> *,
std::vector<std::basic_string<char>,
std::allocator<std::basic_string<char> > > > __first,
__gnu_cxx::__normal_iterator<const std::basic_string<char> *,
std::vector<std::basic_string<char>,
std::allocator<std::basic_string<char> > > > __last) [member function]
> compilation error W1050: The function returns >
"std::vector<std::basic_string<char>,
std::allocator<std::basic_string<char> > > >::pointer" type. You have
to specify a call policies.Be sure to take a look > on `Py++` defined
call policies
std::vector<std::vector<int, std::allocator<int> >,
std::allocator<std::vector<int, std::allocator<int> > > >::pointer
std::vector<std::vector<int, std::allocator<int> >,
std::allocator<std::vector<int, std::allocator<int> > >
>::_M_allocate_and_copy(std::size_t __n,
__gnu_cxx::__normal_iterator<const std::vector<int,
std::allocator<int> > *, std::vector<std::vector<int,
std::allocator<int> >, std::allocator<std::vector<int,
std::allocator<int> > > > > __first,
__gnu_cxx::__normal_iterator<const std::vector<int,
std::allocator<int> > *, std::vector<std::vector<int,
std::allocator<int> >, std::allocator<std::vector<int,
std::allocator<int> > > > > __last) [member function] > compilation
error W1050: The function returns "std::vector<std::vector<int, >
std::allocator<int> >, std::allocator<std::vector<int,
std::allocator<int> > > > >::pointer" type. You have to specify a call
policies.Be sure to take a look > on `Py++` defined call policies
std::vector<std::vector<unsigned int, std::allocator<unsigned int> >,
std::allocator<std::vector<unsigned int, std::allocator<unsigned int>
> > >::pointer std::vector<std::vector<unsigned int,
std::allocator<unsigned int> >, std::allocator<std::vector<unsigned
int, std::allocator<unsigned int> > >
>::_M_allocate_and_copy(std::size_t __n,
__gnu_cxx::__normal_iterator<const std::vector<unsigned int,
std::allocator<unsigned int> > *, std::vector<std::vector<unsigned
int, std::allocator<unsigned int> >,
std::allocator<std::vector<unsigned int, std::allocator<unsigned int>
> > > > __first, __gnu_cxx::__normal_iterator<const
std::vector<unsigned int, std::allocator<unsigned int> > *,
std::vector<std::vector<unsigned int, std::allocator<unsigned int> >,
std::allocator<std::vector<unsigned int, std::allocator<unsigned int>
> > > > __last) [member function] > compilation error W1050: The
function returns > "std::vector<std::vector<unsigned int,
std::allocator<unsigned int> >, > std::allocator<std::vector<unsigned
int, std::allocator<unsigned int> > > > >::pointer" type. You have to
specify a call policies.Be sure to take a look > on `Py++` defined
call policies
std::vector<std::vector<double, std::allocator<double> >,
std::allocator<std::vector<double, std::allocator<double> > >
>::pointer std::vector<std::vector<double, std::allocator<double> >,
std::allocator<std::vector<double, std::allocator<double> > >
>::_M_allocate_and_copy(std::size_t __n,
__gnu_cxx::__normal_iterator<const std::vector<double,
std::allocator<double> > *, std::vector<std::vector<double,
std::allocator<double> >, std::allocator<std::vector<double,
std::allocator<double> > > > > __first,
__gnu_cxx::__normal_iterator<const std::vector<double,
std::allocator<double> > *, std::vector<std::vector<double,
std::allocator<double> >, std::allocator<std::vector<double,
std::allocator<double> > > > > __last) [member function] > compilation
error W1050: The function returns "std::vector<std::vector<double, >
std::allocator<double> >, std::allocator<std::vector<double, >
std::allocator<double> > > >::pointer" type. You have to specify a
call > policies.Be sure to take a look on `Py++` defined call policies
std::vector<std::map<std::basic_string<char>, std::basic_string<char>,
std::less<std::basic_string<char> >, std::allocator<std::pair<const
std::basic_string<char>, std::basic_string<char> > > >,
std::allocator<std::map<std::basic_string<char>,
std::basic_string<char>, std::less<std::basic_string<char> >,
std::allocator<std::pair<const std::basic_string<char>,
std::basic_string<char> > > > > >::pointer
std::vector<std::map<std::basic_string<char>, std::basic_string<char>,
std::less<std::basic_string<char> >, std::allocator<std::pair<const
std::basic_string<char>, std::basic_string<char> > > >,
std::allocator<std::map<std::basic_string<char>,
std::basic_string<char>, std::less<std::basic_string<char> >,
std::allocator<std::pair<const std::basic_string<char>,
std::basic_string<char> > > > > >::_M_allocate_and_copy(std::size_t
__n, __gnu_cxx::__normal_iterator<const
std::map<std::basic_string<char>, std::basic_string<char>,
std::less<std::basic_string<char> >, std::allocator<std::pair<const
std::basic_string<char>, std::basic_string<char> > > > *,
std::vector<std::map<std::basic_string<char>, std::basic_string<char>,
std::less<std::basic_string<char> >, std::allocator<std::pair<const
std::basic_string<char>, std::basic_string<char> > > >,
std::allocator<std::map<std::basic_string<char>,
std::basic_string<char>, std::less<std::basic_string<char> >,
std::allocator<std::pair<const std::basic_string<char>,
std::basic_string<char> > > > > > > __first,
__gnu_cxx::__normal_iterator<const std::map<std::basic_string<char>,
std::basic_string<char>, std::less<std::basic_string<char> >,
std::allocator<std::pair<const std::basic_string<char>,
std::basic_string<char> > > > *,
std::vector<std::map<std::basic_string<char>, std::basic_string<char>,
std::less<std::basic_string<char> >, std::allocator<std::pair<const
std::basic_string<char>, std::basic_string<char> > > >,
std::allocator<std::map<std::basic_string<char>,
std::basic_string<char>, std::less<std::basic_string<char> >,
std::allocator<std::pair<const std::basic_string<char>,
std::basic_string<char> > > > > > > __last) [member function] >
compilation error W1050: The function returns >
"std::vector<std::map<std::basic_string<char>,
std::basic_string<char>, > std::less<std::basic_string<char> >,
std::allocator<std::pair<const > std::basic_string<char>,
std::basic_string<char> > > >, >
std::allocator<std::map<std::basic_string<char>,
std::basic_string<char>, > std::less<std::basic_string<char> >,
std::allocator<std::pair<const > std::basic_string<char>,
std::basic_string<char> > > > > >::pointer" type. You > have to
specify a call policies.Be sure to take a look on `Py++` defined call
> policies
void ompl::msg::log(char const * file, int line, ompl::msg::LogLevel
level, char const * m, ...) [free function] > warning W1053: `Py++`
will not expose function "void ompl::msg::log(char const > * file, int
line, ompl::msg::LogLevel level, char const * m, ...) [free >
function]" - the function has variable-argument list, spicified by
ellipsis > (...).
-- Build type: Release
-- Checking for module 'libspot'
--   No package 'libspot' found
-- Could NOT find spot (missing: SPOT_LIBRARIES SPOT_INCLUDE_DIRS) 
-- Code for module base not found; type "make update_bindings"
-- Code for module control not found; type "make update_bindings"
-- Code for module geometric not found; type "make update_bindings"
-- Code for module tools not found; type "make update_bindings"
-- The following features have been enabled:

 * OMPL_VERSIONED_INSTALL, Whether to install header files in
   <prefix>/include/ompl-X.Y/ompl, where X and Y are the major and minor
   version numbers
 * OMPL_BUILD_PYBINDINGS, Whether to build the Python bindings.
 * OMPL_BUILD_PYTESTS, Whether to build/run the python binding unit tests.
 * OMPL_BUILD_TESTS, Whether to build the unit tests.
 * OMPL_BUILD_DEMOS, Whether to build the OMPL demo programs.

-- The following OPTIONAL packages have been found:

 * Threads, <https://en.wikipedia.org/wiki/POSIX_Threads>
   Pthreads is sometimes needed, depending on OS / compiler.
 * ODE, <http://ode.org>
   The Open Dynamics Engine can be used as a "black box" for kinodynamic planning.
 * flann (required version >= 1.8.3), <https://github.com/mariusmuja/flann>
   If detetected, FLANN can be used for nearest neighbor queries by OMPL.
 * Doxygen, <http://doxygen.org>
   Used to create the OMPL documentation (i.e., https://ompl.kavrakilab.org).
 * Python, <https://www.python.org>
   Used for python bindings.
 * castxml, <https://github.com/CastXML/CastXML>
   Used to generate Python bindings.
 * PkgConfig, <https://www.freedesktop.org/wiki/Software/pkg-config/>
   Used to find (compilation flags for) dependencies.
 * yaml-cpp, <https://github.com/jbeder/yaml-cpp>
   Used for parsing input data for the PlanarManipulator demo.

-- The following REQUIRED packages have been found:

 * Eigen3, <http://eigen.tuxfamily.org>
   A linear algebra library used throughout OMPL.
 * Boost (required version >= 1.58), <https://www.boost.org>
   Used throughout OMPL for data serialization, graphs, etc.

-- The following OPTIONAL packages have not been found:

 * pypy, <https://pypy.org>
   Used to speed up the generation of python bindings.
 * MORSE, <https://www.openrobots.org/wiki/morse>
   OMPL includes a plugin for the MORSE Robot Simulation engine.
 * Triangle, <http://www.cs.cmu.edu/~quake/triangle.html>
   Used to create triangular decompositions of polygonal 2D environments.
 * spot, <http://spot.lrde.epita.fr>
   Used for constructing finite automata from LTL formulae.

-- The following Python modules were found:

 * numpy pyplusplus pygccxml

-- Configuring done
-- Generating done
-- Build files have been written to: /home/dell/ref/ompl-1.6.0/build/Release
[ 33%] Built target update_util_bindings
[ 33%] Creating C++ code for Python module base (see pyplusplus_base.log)


Traceback (most recent call last):
  File "/home/dell/ref/ompl-1.6.0/py-bindings/generate_bindings.py", line 976, in <module>
    globals()['ompl_'+module+'_generator_t']()
  File "/home/dell/ref/ompl-1.6.0/py-bindings/generate_bindings.py", line 154, in __init__
    code_generator_t.__init__(self, 'base', ['bindings/util'], replacement)
  File "/home/dell/ref/ompl-1.6.0/py-bindings/ompl/bindings_generator.py", line 151, in __init__
    self.filter_declarations()
  File "/home/dell/ref/ompl-1.6.0/py-bindings/generate_bindings.py", line 201, in filter_declarations
    self.ompl_ns.class_(f'SpecificParam< {self.string_decl} >').rename('SpecificParamString')
  File "/usr/local/lib/python3.8/dist-packages/pygccxml/declarations/scopedef.py", line 546, in class_
    self._find_single(
  File "/usr/local/lib/python3.8/dist-packages/pygccxml/declarations/scopedef.py", line 464, in _find_single
    found = matcher.get_single(decl_matcher, decls, False)
  File "/usr/local/lib/python3.8/dist-packages/pygccxml/declarations/scopedef.py", line 90, in get_single
    raise runtime_errors.declaration_not_found_t(decl_matcher)
pygccxml.declarations.runtime_errors.declaration_not_found_t: Unable to find declaration. Matcher: [(decl type==class_t) and (name==SpecificParam< std::string >)]
-- Build type: Release
-- Checking for module 'libspot'
--   No package 'libspot' found
-- Could NOT find spot (missing: SPOT_LIBRARIES SPOT_INCLUDE_DIRS) 
-- Code for module base not found; type "make update_bindings"
-- Code for module control not found; type "make update_bindings"
-- Code for module geometric not found; type "make update_bindings"
-- Code for module tools not found; type "make update_bindings"
-- The following features have been enabled:

 * OMPL_VERSIONED_INSTALL, Whether to install header files in
   <prefix>/include/ompl-X.Y/ompl, where X and Y are the major and minor
   version numbers
 * OMPL_BUILD_PYBINDINGS, Whether to build the Python bindings.
 * OMPL_BUILD_PYTESTS, Whether to build/run the python binding unit tests.
 * OMPL_BUILD_TESTS, Whether to build the unit tests.
 * OMPL_BUILD_DEMOS, Whether to build the OMPL demo programs.

-- The following OPTIONAL packages have been found:

 * Threads, <https://en.wikipedia.org/wiki/POSIX_Threads>
   Pthreads is sometimes needed, depending on OS / compiler.
 * ODE, <http://ode.org>
   The Open Dynamics Engine can be used as a "black box" for kinodynamic planning.
 * flann (required version >= 1.8.3), <https://github.com/mariusmuja/flann>
   If detetected, FLANN can be used for nearest neighbor queries by OMPL.
 * Doxygen, <http://doxygen.org>
   Used to create the OMPL documentation (i.e., https://ompl.kavrakilab.org).
 * Python, <https://www.python.org>
   Used for python bindings.
 * castxml, <https://github.com/CastXML/CastXML>
   Used to generate Python bindings.
 * PkgConfig, <https://www.freedesktop.org/wiki/Software/pkg-config/>
   Used to find (compilation flags for) dependencies.
 * yaml-cpp, <https://github.com/jbeder/yaml-cpp>
   Used for parsing input data for the PlanarManipulator demo.

-- The following REQUIRED packages have been found:

 * Eigen3, <http://eigen.tuxfamily.org>
   A linear algebra library used throughout OMPL.
 * Boost (required version >= 1.58), <https://www.boost.org>
   Used throughout OMPL for data serialization, graphs, etc.

-- The following OPTIONAL packages have not been found:

 * pypy, <https://pypy.org>
   Used to speed up the generation of python bindings.
 * MORSE, <https://www.openrobots.org/wiki/morse>
   OMPL includes a plugin for the MORSE Robot Simulation engine.
 * Triangle, <http://www.cs.cmu.edu/~quake/triangle.html>
   Used to create triangular decompositions of polygonal 2D environments.
 * spot, <http://spot.lrde.epita.fr>
   Used for constructing finite automata from LTL formulae.

-- The following Python modules were found:

 * numpy pyplusplus pygccxml

-- Configuring done
-- Generating done
-- Build files have been written to: /home/dell/ref/ompl-1.6.0/build/Release
[ 33%] Built target update_base_bindings
[ 66%] Preparing C++ header file for Python binding generation for module geometric
[ 66%] Built target geometric.h
[ 66%] Creating C++ code for Python module geometric (see pyplusplus_geometric.log)



still alive after 62.0455 seconds!


Replacing member function ::ompl::base::OptimizationObjective::print
Replacing member function ::ompl::base::GoalRegion::print
Replacing member function ::ompl::base::Goal::print
Replacing member function ::ompl::base::ProblemDefinition::print
Replacing member function
::ompl::base::ScopedState<ompl::base::StateSpace>::print
Replacing member function ::ompl::base::Path::print
Replacing member function ::ompl::base::ProjectionMatrix::print
Replacing member function ::ompl::base::ParamSet::print
Replacing member function ::ompl::geometric::PathGeometric::print
Replacing member function ::ompl::geometric::SimpleSetup::print
Replacing member function ::ompl::geometric::PathHybridization::print
Replacing member function
::ompl::geometric::PathGeometric::printAsMatrix
Replacing member function ::ompl::base::Planner::printSettings
Replacing member function
::ompl::base::SpaceInformation::printSettings
Replacing member function ::ompl::base::StateSpace::printSettings
Replacing member function
::ompl::base::CompoundStateSpace::printSettings
Replacing member function
::ompl::base::ProjectionEvaluator::printSettings
Replacing member function ::ompl::geometric::SPARStwo::printDebug
Replacing member function ::ompl::geometric::SPARS::printDebug
still alive after 122.111 seconds!
Traceback (most recent call last):
  File "/home/dell/ref/ompl-1.6.0/py-bindings/generate_bindings.py", line 976, in <module>
    globals()['ompl_'+module+'_generator_t']()
  File "/home/dell/ref/ompl-1.6.0/py-bindings/generate_bindings.py", line 634, in __init__
    code_generator_t.__init__(self, 'geometric', ['bindings/util', 'bindings/base'], \
  File "/home/dell/ref/ompl-1.6.0/py-bindings/ompl/bindings_generator.py", line 154, in __init__
    self.mb.register_module_dependency(dep)
  File "/usr/local/lib/python3.8/dist-packages/pyplusplus/module_builder/boost_python_builder.py", line 142, in register_module_dependency
    db.load( other_module_generated_code_dir )
  File "/usr/local/lib/python3.8/dist-packages/pyplusplus/utils/__init__.py", line 129, in load
    f = open( fpath, 'r+b' )
FileNotFoundError: [Errno 2] No such file or directory: 'bindings/base'
-- Build type: Release
-- Checking for module 'libspot'
--   No package 'libspot' found
-- Could NOT find spot (missing: SPOT_LIBRARIES SPOT_INCLUDE_DIRS) 
-- Code for module base not found; type "make update_bindings"
-- Code for module control not found; type "make update_bindings"
-- Code for module geometric not found; type "make update_bindings"
-- Code for module tools not found; type "make update_bindings"
-- The following features have been enabled:

 * OMPL_VERSIONED_INSTALL, Whether to install header files in
   <prefix>/include/ompl-X.Y/ompl, where X and Y are the major and minor
   version numbers
 * OMPL_BUILD_PYBINDINGS, Whether to build the Python bindings.
 * OMPL_BUILD_PYTESTS, Whether to build/run the python binding unit tests.
 * OMPL_BUILD_TESTS, Whether to build the unit tests.
 * OMPL_BUILD_DEMOS, Whether to build the OMPL demo programs.

-- The following OPTIONAL packages have been found:

 * Threads, <https://en.wikipedia.org/wiki/POSIX_Threads>
   Pthreads is sometimes needed, depending on OS / compiler.
 * ODE, <http://ode.org>
   The Open Dynamics Engine can be used as a "black box" for kinodynamic planning.
 * flann (required version >= 1.8.3), <https://github.com/mariusmuja/flann>
   If detetected, FLANN can be used for nearest neighbor queries by OMPL.
 * Doxygen, <http://doxygen.org>
   Used to create the OMPL documentation (i.e., https://ompl.kavrakilab.org).
 * Python, <https://www.python.org>
   Used for python bindings.
 * castxml, <https://github.com/CastXML/CastXML>
   Used to generate Python bindings.
 * PkgConfig, <https://www.freedesktop.org/wiki/Software/pkg-config/>
   Used to find (compilation flags for) dependencies.
 * yaml-cpp, <https://github.com/jbeder/yaml-cpp>
   Used for parsing input data for the PlanarManipulator demo.

-- The following REQUIRED packages have been found:

 * Eigen3, <http://eigen.tuxfamily.org>
   A linear algebra library used throughout OMPL.
 * Boost (required version >= 1.58), <https://www.boost.org>
   Used throughout OMPL for data serialization, graphs, etc.

-- The following OPTIONAL packages have not been found:

 * pypy, <https://pypy.org>
   Used to speed up the generation of python bindings.
 * MORSE, <https://www.openrobots.org/wiki/morse>
   OMPL includes a plugin for the MORSE Robot Simulation engine.
 * Triangle, <http://www.cs.cmu.edu/~quake/triangle.html>
   Used to create triangular decompositions of polygonal 2D environments.
 * spot, <http://spot.lrde.epita.fr>
   Used for constructing finite automata from LTL formulae.

-- The following Python modules were found:

 * numpy pyplusplus pygccxml

-- Configuring done
-- Generating done
-- Build files have been written to: /home/dell/ref/ompl-1.6.0/build/Release
[ 66%] Built target update_geometric_bindings
[100%] Creating C++ code for Python module control (see pyplusplus_control.log)
Adding array access to class
::ompl::control::RealVectorControlSpace::ControlType
Replacing member function ::ompl::control::SimpleSetup::print
Replacing member function ::ompl::control::PathControl::print
Replacing member function ::ompl::base::GoalRegion::print
Replacing member function ::ompl::base::ProblemDefinition::print
Replacing member function
::ompl::base::ScopedState<ompl::base::StateSpace>::print
Replacing member function ::ompl::base::Goal::print
Replacing member function ::ompl::base::Path::print
Replacing member function ::ompl::base::ProjectionMatrix::print
Replacing member function ::ompl::base::ParamSet::print
Replacing member function ::ompl::geometric::PathGeometric::print
Replacing member function
::ompl::control::RealVectorControlSpace::printSettings
Replacing member function
::ompl::control::DiscreteControlSpace::printSettings
Replacing member function
::ompl::control::SpaceInformation::printSettings
Replacing member function ::ompl::control::ControlSpace::printSettings
Replacing member function
::ompl::control::CompoundControlSpace::printSettings
Replacing member function ::ompl::base::Planner::printSettings
Replacing member function
::ompl::base::SpaceInformation::printSettings
Replacing member function ::ompl::base::StateSpace::printSettings
Replacing member function
::ompl::base::CompoundStateSpace::printSettings
Replacing member function
::ompl::base::ProjectionEvaluator::printSettings
Replacing member function
::ompl::control::RealVectorControlSpace::printControl
Replacing member function
::ompl::control::DiscreteControlSpace::printControl
Replacing member function
::ompl::control::SpaceInformation::printControl
Replacing member function ::ompl::control::ControlSpace::printControl
Replacing member function
::ompl::control::CompoundControlSpace::printControl
Replacing member function ::ompl::control::PathControl::printAsMatrix
Replacing member function
::ompl::geometric::PathGeometric::printAsMatrix
Replacing member function
::ompl::control::ODESolver::getStatePropagator
still alive after 60.0639 seconds!
Traceback (most recent call last):
  File "/home/dell/ref/ompl-1.6.0/py-bindings/generate_bindings.py", line 976, in <module>
    globals()['ompl_'+module+'_generator_t']()
  File "/home/dell/ref/ompl-1.6.0/py-bindings/generate_bindings.py", line 473, in __init__
    code_generator_t.__init__(self, 'control', \
  File "/home/dell/ref/ompl-1.6.0/py-bindings/ompl/bindings_generator.py", line 154, in __init__
    self.mb.register_module_dependency(dep)
  File "/usr/local/lib/python3.8/dist-packages/pyplusplus/module_builder/boost_python_builder.py", line 142, in register_module_dependency
    db.load( other_module_generated_code_dir )
  File "/usr/local/lib/python3.8/dist-packages/pyplusplus/utils/__init__.py", line 129, in load
    f = open( fpath, 'r+b' )
FileNotFoundError: [Errno 2] No such file or directory: 'bindings/base'
-- Build type: Release
-- Checking for module 'libspot'
--   No package 'libspot' found
-- Could NOT find spot (missing: SPOT_LIBRARIES SPOT_INCLUDE_DIRS) 
-- Code for module base not found; type "make update_bindings"
-- Code for module control not found; type "make update_bindings"
-- Code for module geometric not found; type "make update_bindings"
-- Code for module tools not found; type "make update_bindings"
-- The following features have been enabled:

 * OMPL_VERSIONED_INSTALL, Whether to install header files in
   <prefix>/include/ompl-X.Y/ompl, where X and Y are the major and minor
   version numbers
 * OMPL_BUILD_PYBINDINGS, Whether to build the Python bindings.
 * OMPL_BUILD_PYTESTS, Whether to build/run the python binding unit tests.
 * OMPL_BUILD_TESTS, Whether to build the unit tests.
 * OMPL_BUILD_DEMOS, Whether to build the OMPL demo programs.

-- The following OPTIONAL packages have been found:

 * Threads, <https://en.wikipedia.org/wiki/POSIX_Threads>
   Pthreads is sometimes needed, depending on OS / compiler.
 * ODE, <http://ode.org>
   The Open Dynamics Engine can be used as a "black box" for kinodynamic planning.
 * flann (required version >= 1.8.3), <https://github.com/mariusmuja/flann>
   If detetected, FLANN can be used for nearest neighbor queries by OMPL.
 * Doxygen, <http://doxygen.org>
   Used to create the OMPL documentation (i.e., https://ompl.kavrakilab.org).
 * Python, <https://www.python.org>
   Used for python bindings.
 * castxml, <https://github.com/CastXML/CastXML>
   Used to generate Python bindings.
 * PkgConfig, <https://www.freedesktop.org/wiki/Software/pkg-config/>
   Used to find (compilation flags for) dependencies.
 * yaml-cpp, <https://github.com/jbeder/yaml-cpp>
   Used for parsing input data for the PlanarManipulator demo.

-- The following REQUIRED packages have been found:

 * Eigen3, <http://eigen.tuxfamily.org>
   A linear algebra library used throughout OMPL.
 * Boost (required version >= 1.58), <https://www.boost.org>
   Used throughout OMPL for data serialization, graphs, etc.

-- The following OPTIONAL packages have not been found:

 * pypy, <https://pypy.org>
   Used to speed up the generation of python bindings.
 * MORSE, <https://www.openrobots.org/wiki/morse>
   OMPL includes a plugin for the MORSE Robot Simulation engine.
 * Triangle, <http://www.cs.cmu.edu/~quake/triangle.html>
   Used to create triangular decompositions of polygonal 2D environments.
 * spot, <http://spot.lrde.epita.fr>
   Used for constructing finite automata from LTL formulae.

-- The following Python modules were found:

 * numpy pyplusplus pygccxml

-- Configuring done
-- Generating done
-- Build files have been written to: /home/dell/ref/ompl-1.6.0/build/Release
[100%] Built target update_control_bindings
[100%] Built target update_bindings

```

**Comment by zkingston** [comment]
It seems you are compiling against the 1.6.0 release of OMPL, please update to the most recent version on the main branch of this repository, the error you are seeing was fixed in #980.

**Comment by dbdxnuliba** [comment]
ok thanks
