### ISSUE TITLE
Can not import ompl in python after installation by macports in macOS

### ISSUE THREAD

**Issue by mamoll** [ompl/ompl#496]
**[Original report](https://bitbucket.org/ompl/ompl/issue/375) by Xiaoxuehere (Bitbucket: [Xiaoxuehere](https://bitbucket.org/Xiaoxuehere), ).**

----------------------------------------

I successfully installed ompl by macports on macOS High Sierra, but I still can not import ompl in python. The terminal output after I run 

```
#!c++

sudo port sync; sudo port install ompl +app 
```

is as follows:

```
--->  Updating the ports tree
--->  Computing dependencies for ompl
--->  Fetching archive for ompl
--->  Attempting to fetch ompl-1.3.2_0+app+python27.darwin_17.x86_64.tbz2 from https://packages.macports.org/ompl
--->  Attempting to fetch ompl-1.3.2_0+app+python27.darwin_17.x86_64.tbz2 from http://sea.us.packages.macports.org/macports/packages/ompl
--->  Attempting to fetch ompl-1.3.2_0+app+python27.darwin_17.x86_64.tbz2 from http://ywg.ca.packages.macports.org/mirror/macports/packages/ompl
--->  Fetching distfiles for ompl
--->  Verifying checksums for ompl
--->  Extracting ompl
Warning: The +app variant causes some extra code to be compiled that is
distributed under the Rice University Software Distribution License. For
details, please read:
http://ompl.kavrakilab.org/license.html#ricelicense
--->  Configuring ompl
--->  Building ompl
--->  Staging ompl into destroot
Warning: reinplace s|python ./omplweb.py|/opt/local/bin/python2.7 ./omplweb.py|g didn't change anything in /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_science_ompl/ompl/work/destroot/opt/local/share/ompl/webapp/omplweb.py
--->  Installing ompl @1.3.2_0+app+python27
--->  Deactivating ompl @1.3.2_0+python27
--->  Cleaning ompl
--->  Activating ompl @1.3.2_0+app+python27
--->  Cleaning ompl
--->  Updating database of binaries
--->  Scanning binaries for linking errors               
--->  No broken files found.                             
--->  Some of the ports you installed have notes:
  ompl has the following notes:
    If you intend to use ompl_webapp, you need to first launch the redis server:
    
        sudo port load redis
```

I typed python then, and the output is as follows.

```
#!python

Python 2.7.14 (default, Jan  6 2018, 12:12:40) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>import ompl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named ompl
>>>from ompl import base, control, geometric, tools, util
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named ompl
```

Do you know why I still can not use ompl in my python? Thank you!

**Comment by YuhengZhi** [comment]
There is this line in `install-ompl-ubuntu.sh`:
```
cmake ../.. -DPYTHON_EXEC=/usr/bin/python${PYTHONV}
```
which I changed to
```
cmake ../.. -DPYTHON_EXEC=/home/YOUR_USERNAME/anaconda3/envs/YOUR_ENV_NAME/bin/python -DOMPL_PYTHON_INSTALL_DIR=/home/YOUR_USERNAME/anaconda3/envs/YOUR_ENV_NAME/lib/python3.8/site-packages
```
to install ompl in my conda environment. Also I used `pip` to install any python packages needed by OMPL. (The commands in the installation script install many python packages by `sudo apt-get install python3-XXX`, which obviously won't work for your custom environment. So you need to use pip/pip3 after activating your conda environment to install the corresponding packages.)

It seems to work so far.
